class_name CompoundData
## Shared reference data for materials: display names, category buckets, and category
## presentation (order / labels / colours).  Used by the planet Info tab (crust composition
## names) and the Inventory tab (categorised stockpile listing) so there's one source of truth.

## Formula → human-readable name.
const NAMES: Dictionary = {
	# ── Ores / raw minerals ───────────────────────────────────────────────────
	"SiO2":    "Silicon Dioxide",
	"Al2O3":   "Aluminium Oxide",
	"Fe2O3":   "Hematite",
	"MgO":     "Periclase",
	"CaO":     "Calcium Oxide",
	"Na2O":    "Sodium Oxide",
	"K2O":     "Potassium Oxide",
	"TiO2":    "Titanium Dioxide",
	"CaCO3":   "Calcite",
	"FeS2":    "Pyrite",
	"FeO":     "Wüstite",
	"CuFeS2":  "Chalcopyrite",
	"Na2S":    "Sodium Sulfide",
	"H2O":     "Water",
	"NaCl":    "Halite",
	"P2O5":    "Phosphorus Pentoxide",
	"UO2":     "Uraninite",
	"ThO2":    "Thorianite",
	"Coal":    "Coal",
	"Oil":     "Crude Oil",
	# Fractions off the crude still — see the Oil Refining recipe.
	"He3":     "Helium-3",
	# -- Foodstuffs -----------------------------------------------------------
	# Edible mass.  People eat these and nothing else; see Game.FOOD_TYPES.  They are
	# nutritionally interchangeable by mass -- what separates them is what it costs to
	# grow them, which is where the interesting decision lives.
	"Wheat":      "Wheat",
	"Rice":       "Rice",
	"Vegetables": "Vegetables",
	"Fish":       "Fish",
	"Beef":       "Beef",
	"Pork":       "Pork",
	"Chicken":    "Chicken",
	"Algae":      "Culture Algae",
	"CH4":     "Natural Gas",
	"EnrichedU": "Enriched Uranium",
	"FuelOil":  "Fuel Oil",
	"Naphtha":  "Naphtha",
	"Kerosene": "Kerosene",
	"CaSO4":   "Gypsum",
	"MgSO4":   "Epsomite",
	"N2":      "Nitrogen",
	"O2":      "Oxygen",
	"CO2":     "Carbon Dioxide",
	"Ni":      "Nickel",
	"FeS":     "Troilite",
	"MgS":     "Niningerite",
	"MgSiO3":  "Enstatite",
	"Mg2SiO4": "Forsterite",
	"CaSiO3":  "Wollastonite",
	"C":       "Carbon",
	# Trace and giant-planet gases, reachable with an Atmospheric Condenser.
	"Ar":      "Argon",
	"He":      "Helium",
	"Ne":      "Neon",
	"CO":      "Carbon Monoxide",
	"SO2":     "Sulfur Dioxide",
	"HCl":     "Hydrogen Chloride",
	"H2S":     "Hydrogen Sulfide",
	"N2O":     "Nitrous Oxide",
	"PH3":     "Phosphine",
	"C2H2":    "Acetylene",
	"C2H6":    "Ethane",
	# ── Refined metals ────────────────────────────────────────────────────────
	"Fe":      "Iron",
	"Si":      "Silicon",
	"Al":      "Aluminium",
	"Ti":      "Titanium",
	"Mg":      "Magnesium",
	"Ca":      "Calcium",
	"Na":      "Sodium",
	"K":       "Potassium",
	"Cu":      "Copper",
	"Steel":   "Steel",
	# ── Chemicals / components ────────────────────────────────────────────────
	"H2SO4":           "Sulfuric Acid",
	"NH3":             "Ammonia",
	"Plastic":         "Plastic",
	"Graphene":        "Graphene",
	"Ceramic":         "Ceramic",
	"CarbonComposite": "Carbon Composite",
	# ── Manufactured goods ────────────────────────────────────────────────────
	"Concrete":      "Concrete",
	"Glass":         "Glass",
	"SolarPanel":    "Solar Panel",
	"SolarSatellite":"Solar Satellite",
	"Microchip":     "Microchip",
	"Robot":      "Industrial Robot",
	"Battery":       "Battery",
	"Superconductor":"Superconductor",
	"Propellant":    "Rocket Propellant",
	"Rocket":        "Rocket",
	"H2":            "Hydrogen",
	"Aerogel":       "Aerogel",
	"CarbonNanotube":"Carbon Nanotube",
	"Metamaterial":  "Metamaterial",
	"SelfHealingComposite": "Self-Healing Composite",
	"QuantumProcessor":     "Quantum Processor",
	"Antimatter":    "Antimatter",
	"Missile":       "Relativistic Missile",
	"Berserker":     "Berserker Seed",
	"VNProbe":    "von Neumann Probe",
}

## Formula → category bucket (anything not listed defaults to "raw").
const CATEGORIES: Dictionary = {
	# Raw ores and crustal compounds
	"Coal":    "raw",  "Oil":     "raw",
	"He3":     "raw",  "CH4":     "raw",
	"FuelOil": "refined", "Naphtha": "refined", "Kerosene": "refined",
	"EnrichedU": "refined",
	"SiO2":   "raw",  "Al2O3":  "raw",  "Fe2O3":  "raw",  "MgO":    "raw",
	"CaO":    "raw",  "Na2O":   "raw",  "K2O":    "raw",  "TiO2":   "raw",
	"CaCO3":  "raw",  "FeS2":   "raw",  "H2O":    "raw",  "NaCl":   "raw",
	"P2O5":   "raw",  "UO2":    "raw",  "ThO2":   "raw",
	"CuFeS2": "raw",  "Na2S":   "raw",  "C":      "raw",  "FeO":    "raw",
	"CaSO4":  "raw",  "MgSO4":  "raw",  "N2":     "raw",
	"Ni":     "raw",  "FeS":    "raw",  "MgS":    "raw",
	# Refined metals (outputs of smelting / electrolysis recipes)
	"Fe":     "refined",
	"Si":     "refined",
	"Al":     "refined",
	"Ti":     "refined",
	"Mg":     "refined",
	"Ca":     "refined",
	"Na":     "refined",
	"K":      "refined",
	"Cu":     "refined",
	"Steel":  "refined",   # primary structural alloy
	"O2":     "refined",   # electrolytic oxygen — useful industrial gas
	"H2":     "refined",
	# Processed feedstock components
	"Plastic":         "components",
	"Graphene":        "components",
	"Ceramic":         "components",
	"CarbonComposite": "components",
	"H2SO4":           "components",   # industrial chemical feedstock
	"NH3":             "components",
	# Manufactured goods (assembled from refined inputs)
	"Concrete":      "manufactured",
	"Glass":         "manufactured",
	"SolarPanel":    "manufactured",
	"SolarSatellite":"manufactured",
	"Microchip":     "manufactured",
	"Battery":       "manufactured",
	"Superconductor":"manufactured",
	"Propellant":    "manufactured",
	"Rocket":        "manufactured",
	"Aerogel":       "manufactured",
	"CarbonNanotube":"manufactured",
	"Metamaterial":  "manufactured",
	"SelfHealingComposite": "manufactured",
	"QuantumProcessor":     "manufactured",
	"Antimatter":    "manufactured",
	"Missile":       "manufactured",
	"Berserker":     "manufactured",

	# Foodstuffs get their own bucket so the Inventory tab reads as a larder, not as ore.
	"Wheat": "food",
	"Rice": "food",
	"Vegetables": "food",
	"Fish": "food",
	"Beef": "food",
	"Pork": "food",
	"Chicken": "food",
	"Algae": "food",
	"VNProbe": "manufactured",
	"Robot": "manufactured",
}

const CATEGORY_ORDER: Array[String] = ["food", "raw", "refined", "components", "manufactured"]

const CATEGORY_LABELS: Dictionary = {
	"food":         "Food",
	"raw":          "Raw Materials",
	"refined":      "Refined Materials",
	"components":   "Components",
	"manufactured": "Manufactured Goods",
}

const CATEGORY_COLORS: Dictionary = {
	"food":         Color(0.55, 0.80, 0.45),
	"raw":          Color(0.80, 0.70, 0.50),
	"refined":      Color(0.50, 0.80, 0.65),
	"components":   Color(0.50, 0.70, 1.00),
	"manufactured": Color(0.85, 0.55, 0.90),
}

## Encyclopedia text: what each material is, plus any role its sources and uses don't show.
## Where it comes from and what consumes it are derived from the recipe, building, planet and
## mission tables, so those are not repeated here.
const DESCRIPTIONS: Dictionary = {
	# ── Raw materials ─────────────────────────────────────────────────────────
	"SiO2":   "Silica: quartz and the silicate framework of every rocky crust.",
	"Al2O3":  "Alumina, the aluminium ore; a major component of feldspars and clays.",
	"Fe2O3":  "Hematite, ferric oxide. The principal iron ore on Earth and Mars.",
	"FeO":    "Wüstite, ferrous oxide. The dominant iron ore in Venus's basaltic crust; Earth's crust carries none.",
	"FeS2":   "Pyrite, iron disulfide. A lower-grade iron ore and the feed for sulfuric acid.",
	"CuFeS2": "Chalcopyrite, copper iron sulfide: the principal copper ore.",
	"MgO":    "Periclase, magnesium oxide.",
	"MgSO4":  "Epsomite, a magnesium sulfate evaporite.",
	"CaO":    "Quicklime, calcium oxide. Present in crusts and made from calcite.",
	"CaCO3":  "Calcite, calcium carbonate: limestone.",
	"CaSO4":  "Gypsum, a calcium sulfate evaporite.",
	"Na2O":   "Sodium oxide: the soda in soda-lime glass.",
	"Na2S":   "Sodium sulfide. The main sodium ore in Mercury's chemically reduced crust.",
	"NaCl":   "Halite: rock salt and dissolved sea salt.",
	"K2O":    "Potassium oxide, from feldspars and micas.",
	"TiO2":   "Rutile, titanium dioxide: the titanium ore.",
	"P2O5":   "Phosphate rock, reported as phosphorus pentoxide.",
	"UO2":    "Uraninite: natural uranium, 0.72 % fissile U-235. Must be enriched before a reactor can burn it.",
	"ThO2":   "Thorianite: fertile thorium-232, bred into reactor fuel by Thorium Activation.",
	"Coal":   "Organic carbon in sedimentary rock. Fuel for coal stations and the carbon source for smelting and steelmaking; coal burned for power is coal the furnaces do not get.",
	"Oil":    "Crude petroleum, split by Oil Refining into fuel oil, naphtha and kerosene. Far scarcer in the crust than coal.",
	"CH4":    "Methane: natural gas in Earth's crust and a major constituent of the gas giants' atmospheres. Fuel for gas turbines.",
	"He3":    "Helium-3, the fusion fuel. Implanted in airless regolith by the solar wind and present in gas-giant atmospheres; no recipe makes it. Also the high-acceleration launch propellant.",
	"H2O":    "Water: oceans and ice on Earth and Mars, vapour and deep clouds on the gas giants.",
	"N2":     "Nitrogen. Fixed into ammonia by the Haber–Bosch process.",
	"CO2":    "Carbon dioxide, condensed from the atmospheres of Venus, Earth and Mars. CO₂ vented by power stations enters the atmosphere, not any inventory.",
	"Ar":     "Argon, an inert gas.",
	"He":     "Helium-4: the second most abundant gas in the giant planets.",
	"Ni":     "Native nickel, alloyed with the iron of metallic asteroids.",
	"FeS":    "Troilite, iron monosulfide: the sulfide of meteorites and asteroids, about 5 % of stony ones.",
	"C":      "Carbon: the insoluble organic matter and graphite of carbonaceous asteroids. Not coal, but pyrolysis turns it into char that serves as coal does in smelting.",
	"Ne":     "Neon, an inert trace gas.",
	"CO":     "Carbon monoxide.",
	"SO2":    "Sulfur dioxide, Venus's volcanic trace gas.",
	"HCl":    "Hydrogen chloride, a trace gas in Venus's atmosphere.",
	"H2S":    "Hydrogen sulfide, from the deep cloud decks of the giant planets.",
	"N2O":    "Nitrous oxide, a trace greenhouse gas.",
	"PH3":    "Phosphine, present in Jupiter's and Saturn's atmospheres.",
	"C2H2":   "Acetylene, a photochemical trace hydrocarbon.",
	"C2H6":   "Ethane, a photochemical product of methane in giant-planet atmospheres.",
	# ── Refined materials ─────────────────────────────────────────────────────
	"Fe":        "Iron: pig iron from the blast furnace, or native nickel-iron mined directly as metal in the asteroid belt. Converted to steel.",
	"Steel":     "Structural steel, the most widely used construction material in the catalogue.",
	"Si":        "Metallurgical-grade silicon for solar cells, chips and ceramics.",
	"Al":        "Primary aluminium from Hall–Héroult electrolysis. Airframes, spacecraft buses and orbital structures.",
	"Ti":        "Titanium sponge from the Kroll process; pressure hulls.",
	"Mg":        "Magnesium metal.",
	"Ca":        "Calcium metal.",
	"Na":        "Sodium metal; the charge carrier in sodium-ion batteries.",
	"K":         "Potassium metal.",
	"Cu":        "Copper: wiring, interconnects and superconductor feedstock.",
	"O2":        "Oxygen from water electrolysis; the oxidiser in rocket propellant.",
	"H2":        "Hydrogen, from electrolysis or condensed from the giant planets. Feedstock for antimatter.",
	"FuelOil":   "Heavy fuel oil, the refinery fraction oil stations burn.",
	"Naphtha":   "Light refinery fraction; the feedstock for plastics.",
	"Kerosene":  "Refinery middle distillate, combined with oxygen into rocket propellant.",
	"EnrichedU": "Reactor-grade uranium, about 4 % fissile. What a Nuclear Plant burns.",
	# ── Components ────────────────────────────────────────────────────────────
	"Plastic":         "Bulk thermoplastic polymerised from naphtha.",
	"Graphene":        "Single-layer carbon sheet grown by chemical vapour deposition.",
	"Ceramic":         "Heat- and radiation-resistant technical ceramic.",
	"CarbonComposite": "Graphene fibre in a polymer matrix: the tether material of a space elevator.",
	"H2SO4":           "Sulfuric acid, the contact-process base chemical. The clouds of Venus are made of it.",
	"NH3":             "Ammonia: fixed nitrogen for fertiliser and climate-controlled farms.",
	# ── Manufactured goods ────────────────────────────────────────────────────
	"Concrete":             "Portland-cement concrete. Needs no research and no coal to make, so the first mines can always be built. Colony ships land with a supply.",
	"Glass":                "Soda-lime glass for optics, panels and domes.",
	"SolarPanel":           "Photovoltaic modules: silicon wafers laminated in glass on an aluminium frame.",
	"SolarSatellite":       "A Dyson-swarm collector seed. Each Solar Deployment launch carries one to the Sun, where it grows into a shell segment of collectors that beam power to the grid.",
	"Microchip":            "Integrated circuits for avionics, control and computing.",
	"Robot":                "Industrial robot. Joins the workforce: when manufacturing, farm and ranch capacity are staffed, each robot counts as several workers, and it needs no food or housing.",
	"Battery":              "Sodium-ion cells with graphene anodes.",
	"Superconductor":       "High-temperature superconducting tape for magnets and lossless transmission.",
	"Propellant":           "Kerosene and liquid-oxygen launch propellant. Low acceleration: interplanetary transfers take months.",
	"Rocket":               "Expendable launch vehicle. Every launch consumes the vehicles its mission and trajectory require, plus more in proportion to any cargo carried.",
	"Aerogel":              "Supercritically dried silica gel; the insulator for climate envelopes and radiator films.",
	"CarbonNanotube":       "Single-walled carbon nanotubes spun from graphene; megastructure-grade tensile material.",
	"Metamaterial":         "Sub-wavelength-structured ceramic-metal matrix that steers electromagnetic radiation; the aperture material of beamed power.",
	"SelfHealingComposite": "Carbon composite with embedded microvascular healing agents.",
	"QuantumProcessor":     "Superconducting qubit arrays on a cryogenic substrate.",
	"Antimatter":           "Magnetically bottled antiprotons; the highest-acceleration launch propellant.",
	"Missile":              "Relativistic kinetic missile. Fired from the star map at another system, it destroys whatever force is there on arrival. Retaliatory doctrines spend missiles automatically; stockpiled missiles add to deterrence once at least one berserker is held.",
	"Berserker":            "Self-replicating weapon seed. Fired from the star map, it consumes the target system. Holding at least one establishes deterrence, reducing how often hostile civilisations strike.",
	"VNProbe":              "Self-replicating probe seed. Launched from the star map under reconnaissance, relay or colonisation orders, which every copy it builds inherits.",
	# ── Food ──────────────────────────────────────────────────────────────────
	"Wheat":      "Cereal grain. The base of the diet and the feed for every livestock line.",
	"Rice":       "Paddy grain; high yield per unit of land, high water draw.",
	"Vegetables": "Mixed field vegetables.",
	"Algae":      "Photobioreactor algae. Grows under lamps with no soil or season, at very high energy cost per gram; the staple of worlds without a sky. Colony ships land with a stock.",
	"Fish":       "Farmed fish, raised on grain.",
	"Chicken":    "Broiler poultry, raised on grain.",
	"Pork":       "Pork, raised on grain.",
	"Beef":       "Beef, raised on grain; the most grain per gram of any food.",
}
